Сreate StabilityPoolFactory with StabilityPool clone
kumodao/kumo-protocol pull request #297
Opened 2022-12-15 10:20 UTC by arthurka-o

2022-12-17 14:14 UTC, udosson requested changes
Smart contracts and tests look mostly good to me (just small changes here in there)

I skipped the front-end and SDK review for now. Let's do an intensive review together when we merge all the front-end stuff to main.

2022-12-21 00:05 UTC, arthurka-o commented on packages/contracts/contracts/StabilityPoolFactory.sol
> +    function provideToSPbyAsset(
Not sure what do you mean about the `comments`

2022-12-21 00:45 UTC, arthurka-o commented on packages/contracts/test/StabilityPool_KUMOIssuanceTest.js
> +      await contracts.kumoParameters.sanitizeParameters(assetAddress1);
We cannot remove `addNewAssetToSystem` because we create `StabilityPool` in here and connect several contracts.
But we can remove `sanitizeParameters` when we do `addNewAssetToSystem`, because it's already done inside the `addNewAssetToSystem`

2022-12-21 10:10 UTC, udosson requested changes
Everything but the `StabilityPoolFactory` looks good.
@arthurka-o can you please follow the suggestion in the comment?

2022-12-21 10:10 UTC, udosson commented on packages/contracts/contracts/StabilityPoolFactory.sol
> +    function getTotalKUSDDepositsByAsset(address _asset) external view returns (uint256) {
Please remove everything from here till line `108`.
These are just artifacts from me when I was trying something out. We don't use them

2022-12-21 10:17 UTC, udosson commented on packages/contracts/test/TroveManager_RecoveryModeTest.js
> +        stabilityPoolAsset1 = await stabilityPoolFactory.getStabilityPoolByAsset(assetAddress1)
Please change to 
`await deploymentHelper.getStabilityPoolByAsset(contracts, assetAddress1)`

2022-12-21 20:24 UTC, udosson approved these changes
LGTM!

2022-12-21 20:41 UTC, asimpk approved these changes

2022-12-21 21:14 UTC, merged