Feat sdk tests with multi asset
kumodao/kumo-protocol pull request #334
Opened 2023-02-28 14:38 UTC by asimpk

2023-03-02 15:07 UTC, udosson requested changes
@asimpk - The PR already looks very good. Just 1 change and 1 question.

Let's get this merged and then add the system tests with another PR.
Thanks

2023-03-02 15:07 UTC, udosson commented on packages/lib-ethers/test/Kumo.test.ts
> +  describe("shouldGetPrice", () => {
@asimpk - Could you please explain to me why the following tests are part of this test file and why you haven't separated these? Just curious

2023-03-02 15:57 UTC, asimpk commented on packages/lib-ethers/test/Kumo.test.ts
> +  describe("shouldGetPrice", () => {
> @asimpk - Could you please explain to me why the following tests are part of this test file and why you haven't separated these? Just curious

I seperated only those tests which require `Before` block for the redeployment to get a fresh/clean state for those tests, here these tests don't depend on the clean state that's why I keep these in same file

2023-03-02 16:23 UTC, udosson commented on packages/lib-ethers/test/Kumo.test.ts
> +  describe("shouldGetPrice", () => {
Alright. But wouldn't it make sense to move the tests to the test files according to their names?

2023-03-02 16:53 UTC, asimpk commented on packages/lib-ethers/test/Kumo.test.ts
> +  describe("shouldGetPrice", () => {
> Alright. But wouldn't it make sense to move the tests to the test files according to their names?

Yes, we can move them, what do you recommend?

2023-03-03 10:53 UTC, arthurka-o reviewed
Can't we extract those identical pieces of code from the every test?
```
 before(async function () {
                if (network.name !== "hardhat") {
                ...
 ```

2023-03-03 11:51 UTC, asimpk commented
> if (network.name !== "hardhat"
hi @arthurka-o , yes we can but I didn't test it by extracting this one-liner condition where the context is involved, `before`, `beforeEach` are the hooks provided by mocha, and in the condition is `this.skip`, `this`  refers to Mocha.Context , so I was not sure if it will behave as I expected or not, I left it just as it was before the separation and extracted a few functions in testUtils

2023-03-03 14:19 UTC, arthurka-o approved these changes

2023-03-03 15:21 UTC, merged