Feat design implementation
kumodao/kumo-protocol pull request #351
Opened 2023-05-11 15:06 UTC by asimpk

2023-05-17 12:27 UTC, udosson commented
@asimpk - is this the recent state of the front end deployed to the server?

Can you please list what features are included in this PR`?

2023-05-17 18:17 UTC, asimpk commented
> @asimpk - is this the recent state of the front end deployed to the server?
> 
> Can you please list what features are included in this PR`?

hi @udosson, yes the deployed frontend is synced with this PR. 
Features or Major Changes:
SDK:
Multi-Asset support.
State Management.
Tests for multi-asset.

Frontend:
Design Update
Multi-Asset UI Components
Wallet Integration

2023-05-23 13:53 UTC, udosson requested changes
@asimpk - thanks for the PR. It already looks very good.
My comments are mainly related to the generic architecture and the differentiation between test and production-ready systems.

2023-05-23 13:53 UTC, udosson commented on packages/contracts/contracts/KumoFaucet.sol
Let's move this file to `./contracts/TestContracts`. What to you think, @arthurka-o

2023-05-23 13:53 UTC, udosson commented on packages/dev-frontend/src/components/AddAssetButton.tsx
> +import React, { useEffect, useState } from "react";
Is this how this should be written? Or should it be:
`import { React,  useEffect, useState } from "react";`

2023-05-23 13:53 UTC, udosson commented on packages/dev-frontend/src/components/RiskyTroves.tsx
Can the `nbc` and `csc` parts be more generic? How would this work if we added more features? This way, we also need to add the assets hard-coded here

2023-05-23 13:53 UTC, udosson commented on packages/dev-frontend/src/hooks/DashboardContext.tsx
Let's make this more generic.
e.g.
totalColl[NBC] or so

2023-05-23 13:53 UTC, udosson commented on packages/lib-ethers/src/BlockPolledKumoStore.ts
> +              testTokensTransfered: false
@asimpk - can you start thinking about a test and a production deployment? How should these be different and how to deploy these based on a given parameter? 
e.g. testTokens will only be needed for the test version and shouldn't be added to the production-ready system

2023-05-23 15:20 UTC, asimpk commented on packages/dev-frontend/src/components/AddAssetButton.tsx
> +import React, { useEffect, useState } from "react";
Hi, this is related to named and default exports and imports in javascript,
We have to write in {} for importing the named modules and Defaults imported as React.

2023-05-23 15:21 UTC, asimpk commented on packages/dev-frontend/src/components/AddAssetToken/context/AssetViewProvider.tsx
> +import React, { useState, useCallback, useEffect, useRef } from "react";
> Same here. Or is this they way to import `React`?

explained in above comment

2023-05-25 10:21 UTC, udosson commented
@asimpk - the changes look good in the code. Have you tested the main function in the front end? Maybe you can try to use your E2E tests as an additional check.

2023-05-25 12:12 UTC, asimpk commented
> @asimpk - the changes look good in the code. Have you tested the main function in the front end? Maybe you can try to use your E2E tests as an additional check.

My test work is different, and maybe needs some fixes also I want to update that branch with the latest code from the dev after this merge

2023-05-26 06:04 UTC, udosson commented
Alright. I'm okay with that.

2023-05-26 06:05 UTC, udosson approved these changes

2023-05-26 06:05 UTC, udosson commented
@arthurka-o - can you please also have a look at this PR? thx

2023-05-26 11:52 UTC, arthurka-o approved these changes

2023-06-05 05:34 UTC, merged