fix: frontend failed tests fixed
kumodao/kumo-protocol pull request #376
Opened 2023-08-14 17:54 UTC by asimpk

Tests were failing because of wrong using wrong test accounts. Now correct test accounts with names added. One test is commented will likely to be updated after backend changes.

2023-08-15 09:45 UTC, marceljay reviewed
First of all, good on ya for using the semantic commit with body. 
However, I'm not sure what exactly is fixed, since you are getting rid of magic numbers and make the tests more readible via names (Alice etc.).

If the fix means, skipping a test, that is not really a fix ;-)

Also, I would usually split this is up into two commits, one where you replace the magic numbers  and then another where you actually fix the tests.

2023-08-15 09:45 UTC, marceljay commented on packages/dev-frontend/tests/e2e/specs/kumo-app-e2e-testing.js
> +  // it('should switch to Alice and KUMO rewards should be greater than 0 (get rewarded when Bob joined Stability Pool)', () => {
I suggest using `it.skip` here instead of using comments. That way it shows up in the console so the dev knows which tests are currently skipped.

2023-08-15 12:09 UTC, marceljay requested changes
Please use rebasing.

First commit and second commit have some identical changes, the fact that changes are displayed again seems like a Github bug to me. This first commit should be dropped, since it also uses the uncommenting.
Then merge is used, that can be avoided by rebasing on the latest `dev` branch.

2023-08-15 12:14 UTC, marceljay commented
Very much a Github UI Glitch! Really annoying. Where do the billions of dollars go??
```
┌──(mav㉿Marcels-MacBook-Pro)-[~/dev/eth/kumo-protocol]-[fix-frontend-tests]
└─$ git log -5
commit 1ce619a600b83b38189d48459cefe02f52b9f080 (HEAD -> fix-frontend-tests, asim/fix-frontend-tests)
Author: asimpk <asimpk.dev@gmail.com>
Date:   Tue Aug 15 15:44:57 2023 +0500

    test: skip the specific test for future fix
    
--- a/packages/dev-frontend/tests/e2e/specs/kumo-app-e2e-testing.js
+++ b/packages/dev-frontend/tests/e2e/specs/kumo-app-e2e-testing.js
@@ -325,25 +325,25 @@ describe('KUMO App e2e testing spec', () => {
     cy.contains('ADJUST').should('be.visible');
   });
 
-  // it('should switch to Alice and KUMO rewards should be greater than 0 (get rewarded when Bob joined Stability Pool)', () => {
-  //   cy.switchToMetamaskWindow();
-  //   cy.switchMetamaskAccount(testUsers.Alice);
-  //   cy.resetMetamaskAccount();
-  //   cy.switchToCypressWindow();
-  //   cy.visit('/');
-  //   cy.reload();
-  //   cy.contains('CONNECT').click();
-  //   cy.contains('MetaMask').click();
-  //   cy.contains('DISCONNECT').should('be.visible');
-  //   if (cy.get('#close-window')) {
-  //     cy.get('#close-window').click();
-  //   }
-  //   cy.contains('Staking').click();
-  //   cy.contains('Stability Pool Staking').click();
-  //   cy.contains('NBC Stability Pool Staking').click();
-  //   cy.contains('ADJUST').should('be.visible');
-  //   cy.get('#deposit-reward > div > span').first().invoke('text').then(parseInt).should('be.greaterThan', 0)
-  // })
+  it('should switch to Alice and KUMO rewards should be greater than 0 (get rewarded when Bob joined Stability Pool)', () => {
+    cy.switchToMetamaskWindow();
+    cy.switchMetamaskAccount(testUsers.Alice);
+    cy.resetMetamaskAccount();
+    cy.switchToCypressWindow();
+    cy.visit('/');
+    cy.reload();
+    cy.contains('CONNECT').click();
+    cy.contains('MetaMask').click();
+    cy.contains('DISCONNECT').should('be.visible');
+    if (cy.get('#close-window')) {
+      cy.get('#close-window').click();
+    }
+    cy.contains('Staking').click();
+    cy.contains('Stability Pool Staking').click();
+    cy.contains('NBC Stability Pool Staking').click();
+    cy.contains('ADJUST').should('be.visible');
+    cy.get('#deposit-reward > div > span').first().invoke('text').then(parseInt).should('be.greaterThan', 0)
+  })
 
   it('should switch to Carol account and open the Vault', () => {
     cy.switchToMetamaskWindow();
~
~
~
~
~
~
~
~
~
~
~
(END)

```

2023-08-15 16:06 UTC, marceljay approved these changes
LGTM, Awesome!

2023-08-16 12:10 UTC, marceljay commented
Merging this now because we need this desperately. Kudos again for the great commit messages @asimpk !

2023-08-16 12:10 UTC, merged

2023-08-16 19:56 UTC, asimpk commented
> Merging this now because we need this desperately. Kudos again for the great commit messages @asimpk !

Thanks @marceljay , setting up standards is the great start from you.